require 'active_record/version'
require 'grouped_scope/errors'
require 'grouped_scope/self_grouping'

require 'grouped_scope/arish/reflection'
require 'grouped_scope/arish/associations/collection_association'
require 'grouped_scope/arish/associations/builder/grouped_collection_association'
require 'grouped_scope/arish/associations/association_scope'
require 'grouped_scope/arish/relation/predicate_builer'
require 'grouped_scope/arish/base'
